### ISSUE TITLE
Improve docker-connection options

### ISSUE THREAD

**Issue by Silex** [Silex/docker-api.el#1]
Right now the options to configure the docker connection is tightly coupled to how `make-network-process` works, which has an API kinda bizarre and unintuitive.

Refactor the options so it parses ONE url instead, like:

``` elisp
(setq docker-connection-url "file:///var/docker/docker.sock")
(setq docker-connection-url "http://somehost.com:1234")
```

**Comment by marsam** [comment]
Becuase [docker-remote](https://docs.docker.com/reference/api/docker_remote_api/) is a REST api over an unix socket I think could be a better idea to use `url-http.el` somehow.

I'll probably couldn't work on this until the next weekend, sorry

**Comment by Silex** [comment]
No worries. I'm also quite swamped but I'll try to finish the basics soonish so we can start shipping :)

The problem about `url-http.el` is that AFAIK it doesn't support unix domain socket. None of the "HTTP" api for emacs does, except `make-network-process`. All of the emacs HTTP libs wrappers I found use `url-retrieve`...

**Comment by marsam** [comment]
I mean, we can  ~~steal~~ use most of the code from `url.el` (for example [url-open-stream](http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/url/url-gw.el?h=d3605ed#n206) or at least the process filters) to make it to connect to a socket instead of a host.

**Comment by Silex** [comment]
Well, `make-network-process` can also connect to sockets :)

Otherwise, yeah let's just use https://github.com/tkf/emacs-request or `url-open-stream`, but I'm not sure wether connecting to docker with two different methods is a good idea. Just to be clear, `url-open-stream`
can **NOT** connect to unix domain sockets.

Right now, until we find another method, we are forced to use `make-network-process` 99% of the time because most installations use an unix domain socket. When an installation uses plain sockets, we can also use `make-network-process`, or use another emacs lib. It makes more sense to me to continue using `make-network-process` for both cases given we have no choice for one of the case.

This issue was not really about using `make-network-process` or not, but rather to refactor the _user options_ so they look better and are abstracted from the implementation.

**Comment by tzz** [comment]
@Silex could you please consider also supporting Tramp syntax somehow? It would be ridiculously useful to me to be able to use Docker remotely over Tramp/SSH. I don't have a strong opinion on the syntax but something like `/user@host:/var/docker/docker.sock` could be good enough.

If you want to discuss this in a separate issue I'll go there, I just thought this discussion was relevant :) Thanks!

**Comment by Silex** [comment]
@tzz: do you mean https://github.com/emacs-pe/docker-tramp.el ?

Anyway, this issue was solved recently so I'll close it. Open a new one if you meant something else.
