### ISSUE TITLE
with-docker-daemon

### ISSUE THREAD

**Issue by Silex** [Silex/docker-api.el#5]
@tzz

> @Silex since you could be dealing with multiple daemons across multiple machines, maybe something like this would make sense:
> 
> (with-docker-daemon mydaemon
>   (docker-image-pull ...))
> Without the with-docker-daemon wrapper, all the operations then implicitly work on the local Docker daemon, as users would expect.
> 
> It's unclear what happens if you take an image from one daemon and hand it to another. Maybe across daemons, the image is serialized as just a string... and other things are just not portable, like running processes, but could again be serialized to strings.

**Comment by Silex** [comment]
Hum, I think it'd be pretty easy to write a macro like:

``` elisp
(with-docker-api-host "tcp://11.22.33.44:12345"
  (docker-image-rm id)) ;; delete image remotely
```

Would you be happy with that?

**Comment by tzz** [comment]
Yeah, that would work exactly. It's just a convenience right now but could be much more powerful if you supported Swarm or some other clustering solution. I would name it `with-docker-api-connection` because the connection could be to a TCP port, a local socket, or something else as long as it speaks the API.

Thanks!

**Comment by Silex** [comment]
Alright, will implement it soonish.

**Comment by Silex** [comment]
@tzz: checkout what I just pushed:

``` elisp
(docker-api-with-connection "tcp://1.2.3.4:555"
  (docker-api-images))

(docker-api-with-connection "unix:///some/path/docker.sock"
  (docker-api-images))
```

**Comment by tzz** [comment]
Beautiful, thank you!

**Comment by Silex** [comment]
:+1: 

Now I just need to actually start implementing most of the actions :-)
