### ISSUE TITLE
Docker API over Tramp

### ISSUE THREAD

**Issue by tzz** [Silex/docker-api.el#6]
Could you please consider also supporting Tramp syntax somehow? It would be ridiculously useful to me to be able to use Docker remotely over Tramp/SSH. I don't have a strong opinion on the syntax but something like `/user@host:/var/docker/docker.sock` could be good enough.

https://github.com/emacs-pe/docker-tramp.el calls shell commands remotely, while access to the actual API would be much more reliable and scalable.

**Comment by Silex** [comment]
I don't understand how the docker api and TRAMP can be related... can you explain with a bit more details what you're trying to do? I mean, TRAMP is meant to provide a shell & list files. The docker remote api is nothing like that.

Just to be clear, https://github.com/emacs-pe/docker-tramp.el provides a shell & list files inside containers through TRAMP.

Anyway, would #5 answer your need? it seems pretty easy to implement.

**Comment by tzz** [comment]
Tramp supports plugin methods. So we'd write a new connection plugin that, given a SSH connection, will talk to the remote API socket. This is already built into SSH for remote port forwarding, and can probably be implemented for socket files pretty easily too: https://www.gnu.org/software/tramp/#Connection-types so it's just a matter of writing the plugin or tuning the Tramp connection parameters to wrap the necessary arguments.

This would let the user talk to any remote Docker daemon as long as the user has a SSH connection to it, which is really useful in secure environments where there's no VPN or external access.

I'm explaining all this before I start writing code so you can understand the usage and tell me if it's not what you want in your repo (in which case I'll try to implement it for myself).

Thanks again.

**Comment by Silex** [comment]
Sorry but I still don't understand what you'd do with such a TRAMP plugin. Let me show you some examples:

`C-x C-f /ssh:root@host.com:/var/log/syslog` # edit /var/log/syslog using SSH
`C-x C-f /docker:167f0337aef8:/var/log/syslog` # edit file /var/log/syslog in container 167f0337aef8
`C-x C-f /ftp:user@google.com:/web/index.html` # edit file index.html on FTP google.com

All these example is what _currently_ exists in emacs.

What I understand from what you're saying is that you would like something like:

`C-x C-f /docker-api:root@host.com:/what/the/hell/goes/here` # ????

What would that do?

**Comment by tzz** [comment]
Hmm. So let's say you have shell access to the remote machine, right? Your base Tramp URL for the remote connection would then be `/ssh:root@host.com:`, let's say that's the `BASE`.

So now you ask Tramp to run `BASE/usr/bin/curl localhost:2345` and simply treat it as a regular Tramp command, so you can write the invocation JSON to a file or pass it inline. Or you could run netcat if you want raw TCP. From that, you read the response back and there's your conversation with the API. Tramp will take care of opening the connection and keeping it alive and everything else that's needed. From the user's perspective, they are just doing `docker-api-with-connection "/docker-api:root@host.com"` and the rest Just Works.

I think the equivalent conversation with the socket, so you don't even have to open a TCP port, can be done with `socat` but I'd have to look into it.

**Comment by Silex** [comment]
Oh, I get it now. Basically you want SSH tunnel support.

I think the answer from http://stackoverflow.com/questions/17246119/emacs-how-to-use-ssh-tunnel-to-connect-to-remote-mysql should work in your case... but not until I refactored docker-api so it uses CURL.

Right now it uses `make-network-process`, which is not TRAMP aware as far as I know.

I have something almost working with request.el, I'll keep you posted.

**Comment by tzz** [comment]
Exactly, yeah!

I think it would be really nice if the docker socket was usable by default, because by default only the socket is enabled. If you get it working with `curl` I can probably do the socket piece :)

**Comment by Silex** [comment]
Pending https://github.com/tkf/emacs-request/pull/43 this should be possible!

Basically:

``` elisp
(let ((default-directory "/ssh:host.myhost.com:"))
  (docker-api-images))
```

Use `docker-api-with-connection` inside the let block if you need to connect somewhere else than `/var/run/docker.sock`.

**Comment by tzz** [comment]
That's awesome, thanks. Let me know if you need some testing.

**Comment by Silex** [comment]
Alright, it was merged. Now I need to switch over using `request.el` instead of my own `make-network-process` thing. I'll ping you when I'm done.

**Comment by Silex** [comment]
@tzz: okay, I just pushed my changes. It'd work!

**Comment by tzz** [comment]
The docs and the code look great. Thank you for working on this.
